### ISSUE TITLE
API_Msoro.ino: several 1000 ms delays scattered throughout code

### ISSUE THREAD

**Issue by achang46** [arunniddish/API#2]
Several 1 second delays are scattered throughout the code. Many are placed between consecutive serial reads associated with a single command, e.g. "start" -> delay -> LED on -> delay -> LED off -> ... -> delay -> 'A7'.

These can impact time-sensitive execution of gaits (e.g. commanded via Matlab -> serial -> Arduino). There's a similar, though less urgent, concern with the "define" serial command.

Assume these delays were in place for ease of troubleshooting/debugging during development. Should remove these now/if no longer needed for this purpose.

**Comment by arunniddish** [comment]
These delays were initially placed for troubleshooting purpose but later they turned out to be essential to avoid buffer overwriting. But they are not the final delay values and needs to be changed to lower values.

**Comment by achang46** [comment]
The "delay(1000)" instances in question are in API_Msoro.ino; they all happen after HIGH/LOW digitalWrite()'s during "define" or "start" processing - I'm assuming these digitalWrite()'s maybe trigger an LED long enough for you to observe and confirm serial receipts, during development and testing. These delays don't seem to follow any serial write commands though; they precede serial reads, it seems counter-intuitive that delays (on the receiving end) would make a serial read buffer size issue any better?

If serial rx/tx buffer sizes are the issue and onboard memory usage isn't limiting, have you tried recompiling the related Arduino libraries with a greater value?

**Comment by achang46** [comment]
[Meeting, Alex-Arun, 4/15/22] 
- 1 sec. delays on Aruidno side are just intended to manage LED notifications (removing them is a non-issue)
- Finding that removing delays in the Matlab script (that sends successive commands through serial to Arduino), results in incorrect command processing on the Aruidno side - e.g. LEDs/motors not being commanded as expected
- Arun actively investigating why serial sends (e.g. from Matlab to Arduino) seem to only be processed correctly (by Arduino) when large delays are placed between successive serial sends (Matlab -> Arduino)
